export const ADDED_VEHICLES = 'ADDED_VEHICLES';
export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const FETCHED_VEHICLES = 'FETCHED_VEHICLES';
export const UPDATED_VEHICLES = 'UPDATED_VEHICLES';
export const DELETED_VEHICLES = 'DELETED_VEHICLES';

export const ADDED_CUSTOMERS = 'ADDED_CUSTOMERS';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCHED_CUSTOMERS = 'FETCHED_CUSTOMERS';
export const UPDATED_CUSTOMERS = 'UPDATED_CUSTOMERS';
export const DELETED_CUSTOMERS = 'DELETED_CUSTOMERS';

export const ADDED_APPOINTMENTS = 'ADDED_APPOINTMENT';
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENT';
export const FETCHED_APPOINTMENTS = 'FETCHED_APPOINTMENT';
export const UPDATED_APPOINTMENTS = 'UPDATED_APPOINTMENT';
export const DELETED_APPOINTMENTS = 'DELETED_APPOINTMENT';
